Repository SENG499-COMPANY4/Algorithm-2, pull requests merged in 2023-06, with the labels that each got.

#16 First Iteration of class size predictor
  app.py
  class_size_predictor.py
  requirements.txt
Labels: enhancement

#49 Commit message:
  .github/workflows/master_algo-2-app.yml
  .github/workflows/staging_algo-2-app-staging.yml
  .gitignore
  requirements.txt
  test_integration.py
Labels: Testing

#51 Update README.md
  README.md
Labels: documentation
